packages:
  - "packages/**"
  - "playground"
  - "!**/test/**"

overrides:
  "rollup@>=4.0.0 <4.22.4": ">=4.22.4"
  "cross-spawn@<7.0.5": ">=7.0.5"
  "@eslint/plugin-kit@<0.2.3": ">=0.2.3"
  "esbuild@<0.25.0": ">=0.25.0"
  "@babel/runtime@<7.26.10": ">=7.26.10"

# Don't automatically link to workspace packages.
# One must use the explicit `workspace:...` protocol instead.
#
# https://pnpm.io/npmrc#link-workspace-packages
linkWorkspacePackages: false

autoInstallPeers: true
dedupePeerDependents: true
strictPeerDependencies: true