packages:
  - "packages/**"
  - "playground"
  - "!**/test/**"

catalog:
  "@preact/signals-core": 1.14.2

  # Dev Dependencies
  "@changesets/cli": ^2.31.0
  "@eslint/js": ^9.39.4
  "@mdi/font": ^7.4.47
  "@types/node": ^24.13.2
  "@vitejs/plugin-vue": ^6.0.6
  concurrently: ^10.0.3
  esbuild: ^0.28.0
  eslint: ^9.39.4
  eslint-config-prettier: ^10.1.8
  eslint-plugin-headers: 1.3.4
  eslint-plugin-vue: ^10.9.1
  happy-dom: ^20.9.0
  husky: ^9.1.7
  lint-staged: ^17.0.4
  prettier: ^3.8.3
  rimraf: ^6.1.3
  tsx: ^4.21.0
  typedoc: ^0.28.19
  typescript: ^6.0.3
  typescript-eslint: ^8.59.3
  vite: ^8.0.12
  vitest: ^4.1.6
  vue: ^3.5.34
  vue-eslint-parser: ^10.4.0
  vuetify: ^3.12.6

# Empty object so renovate does not error out
overrides: {}

peerDependencyRules:
  allowedVersions:
    typescript: "*"

# Empty object so renovate does not error out
auditConfig: {}

minimumReleaseAge: 4320 # 3 days in minutes
minimumReleaseAgeExclude:
  - "@open-pioneer/*"
  - "@conterra/*"

# Don't automatically link to workspace packages.
# One must use the explicit `workspace:...` protocol instead.
#
# https://pnpm.io/npmrc#link-workspace-packages
linkWorkspacePackages: false

autoInstallPeers: true
dedupePeerDependents: true
strictPeerDependencies: true
allowBuilds:
  esbuild: true
