packages:
  - "packages/**"
  - "playground"
  - "!**/test/**"

catalog:
  "@preact/signals-core": 1.12.2

  # Dev Dependencies
  "@changesets/cli": ^2.29.8
  "@eslint/js": ^9.39.2
  "@mdi/font": ^7.4.47
  "@types/node": ^22.19.7
  "@vitejs/plugin-vue": ^6.0.3
  concurrently: ^9.2.1
  esbuild: ^0.27.2
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-headers: 1.3.3
  eslint-plugin-vue: ^10.7.0
  happy-dom: ^20.3.7
  husky: ^9.1.7
  lint-staged: ^16.2.7
  prettier: ^3.8.1
  rimraf: ^6.1.2
  tsx: ^4.21.0
  typedoc: ^0.28.16
  typescript: ^5.9.3
  typescript-eslint: ^8.53.1
  vite: ^7.3.1
  vitest: ^4.0.18
  vue: ^3.5.27
  vue-eslint-parser: ^10.2.0
  vuetify: ^3.11.7

overrides:
  "rollup@>=4.0.0 <4.22.4": ">=4.22.4"
  "cross-spawn@<7.0.5": ">=7.0.5"
  '@eslint/plugin-kit@<0.2.3': '>=0.2.3'
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  "esbuild@<0.25.0": ">=0.25.0"
  "@babel/runtime@<7.26.10": ">=7.26.10"
  "brace-expansion@>=1.0.0 <=1.1.11": "^1.1.12"
  "brace-expansion@>=2.0.0 <=2.0.1": "^2.0.2"
  "tmp@<=0.2.3": "^0.2.4"

onlyBuiltDependencies:
  - esbuild

# Don't automatically link to workspace packages.
# One must use the explicit `workspace:...` protocol instead.
#
# https://pnpm.io/npmrc#link-workspace-packages
linkWorkspacePackages: false

autoInstallPeers: true
dedupePeerDependents: true
strictPeerDependencies: true
