packages:
  - "packages/**"
  - "playground"
  - "!**/test/**"

catalog:
  "@preact/signals-core": 1.14.4

  # Dev Dependencies
  "@changesets/cli": ^2.31.1
  "@eslint/js": ^9.39.5
  "@mdi/font": ^7.4.47
  "@types/node": ^24.13.3
  "@vitejs/plugin-vue": ^6.0.8
  concurrently: ^10.0.5
  esbuild: ^0.28.2
  eslint: ^9.39.5
  eslint-config-prettier: ^10.1.8
  eslint-plugin-headers: 1.3.4
  eslint-plugin-vue: ^10.10.0
  happy-dom: ^20.11.6
  husky: ^9.1.7
  lint-staged: ^17.3.0
  prettier: ^3.9.6
  rimraf: ^6.1.3
  tsx: ^4.23.12
  typedoc: ^0.28.20
  typescript: ^6.0.3
  typescript-eslint: ^8.67.0
  vite: ^8.2.2
  vitest: ^4.1.11
  vue: ^3.5.41
  vue-eslint-parser: ^10.4.1
  vuetify: ^3.13.2

# Empty object so renovate does not error out
overrides:
  # https://github.com/advisories/GHSA-6v5v-wf23-fmfq
  "markdown-it@<=14.1.1": "^14.1.2"

  # https://github.com/advisories/GHSA-22p9-wv53-3rq4
  "linkify-it@<=5.0.0": "^5.0.1"

peerDependencyRules:
  allowedVersions:
    typescript: "*"

# Empty object so renovate does not error out
auditConfig:
  ignoreGhsas:
    # js-yaml: https://github.com/advisories/GHSA-h67p-54hq-rp68
    - GHSA-h67p-54hq-rp68

minimumReleaseAge: 4320 # 3 days in minutes
minimumReleaseAgeExclude:
  - "@open-pioneer/*"
  - "@conterra/*"

# Don't automatically link to workspace packages.
# One must use the explicit `workspace:...` protocol instead.
#
# https://pnpm.io/npmrc#link-workspace-packages
linkWorkspacePackages: false

autoInstallPeers: true
dedupePeerDependents: true
strictPeerDependencies: true
allowBuilds:
  esbuild: true
