name: Install
description: Install pnpm dependencies
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: 24.18.0
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
