name: Build and release

on:
  push:
  workflow_dispatch:

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Run tests
        run: |
          pnpm lint
          pnpm build
          pnpm check-types
          pnpm test

  version:
    name: Update release PR or publish
    if: github.ref == 'refs/heads/main'
    concurrency: version-${{ github.ref }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - checks
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - id: changesets
        name: Create release pull request or publish to npm
        uses: changesets/action@v1
        with:
          version: "pnpm run ci:version"
          publish: "pnpm run ci:publish"
          commit: "[RELEASE] Update package versions"
          title: "[RELEASE] Update package versions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NO_VERIFY: "1" # don't run git hooks on simple version commits

  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build documentation
        run: |
          pnpm build-docs

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: dist/docs
          retention-days: 1

  deploy:
    if: github.ref == 'refs/heads/main'
    concurrency: deploy-${{ github.ref }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - checks
      - docs
      - version
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          target-folder: ${{ needs.version.outputs.published == 'true' && 'latest' || 'dev' }}
